name: Deploy JCL to Mainframe

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Zowe CLI and FTP Plugin
        run: |
          npm install -g @zowe/cli@latest
          zowe plugins install @zowe/zos-ftp-for-zowe-cli@latest
          
      - name: Upload JCL to Mainframe
        run: |
          npx zowe zos-ftp upload file-to-data-set "hello-world.jcl" "TRAIN70.JCL(HWORLD)" \
            --host ${{ secrets.MAINFRAME_HOST }} \
            --port 21 \
            --user ${{ secrets.MAINFRAME_USER }} \
            --password ${{ secrets.MAINFRAME_PASSWORD }} \
            --secure-ftp false
            
      - name: Submit JCL Job
        run: |
          npx zowe zos-ftp submit data-set "TRAIN70.JCL(HWORLD)" \
            --host ${{ secrets.MAINFRAME_HOST }} \
            --port 21 \
            --user ${{ secrets.MAINFRAME_USER }} \
            --password ${{ secrets.MAINFRAME_PASSWORD }} \
            --secure-ftp false \
            --wait-for-active
